trigger:
- main

jobs:
- job: Build
  displayName: 'Build Job'
  pool:
    name: Default 

  steps:
  - script: |
      python -m venv env
      .\env\Scripts\activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Uncomment the following lines if you have tests to run
  # - script: |
  #     python -m unittest discover tests
  #   displayName: 'Run tests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)'
      artifactName: 'backend'
    displayName: 'Publish Artifact'
